name: OWM Build and Test
on:
  push:
    branches: [main, actions]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./owm
    strategy:
      matrix:
        go-versions: [1.19.x,1.24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test --cover
